"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./Components/CardContext";
// import CartProvider from "./Components/Contextreducer";
// import CartProvider from "./Components/Contextreducer";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <CartProvider>

      <body className={inter.className}>{children}</body>
      </CartProvider>

      
    </html>

    
  );
}
